#
# This file is generated by the POM from the copy at /src/main/resources/create-project.sh
# So, modify that copy only!
#
groupId="$1"
artifactId="$2"
version="$3"

if [[ "$#" < 3 ]]; then
	cat <<EOT


Creates a new command line project from our archetype.  
	
	$(basename $0) <groupId> <artifactId> <version> 

EOT
	exit 1
fi

# First, download the archetype
mvn dependency:get \
  -Dartifact=uk.ac.ebi.maven:cli-archetype:3.0.1\
  -DremoteRepositories=https://mbrandizi.jfrog.io/artifactory/maven
     
# So that now we can use it from the local repo
#
mvn archetype:generate \
	-DgroupId=$groupId -DartifactId=$artifactId -Dversion=$version \
	-DarchetypeGroupId=uk.ac.ebi.maven \
	-DarchetypeArtifactId=cli-archetype \
	-DarchetypeVersion=3.0.1 \
	-DinteractiveMode=false 
